name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: kadmiel
        DOCKER_PASSWORD: ${{secrets.kadmiel}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python:v1.0
      
    - name: Docker Tag
      run: docker tag python:v1.0 kadmiel/python
      
    - name: Docker Push
      run: docker push kadmiel/python
