name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username:  kadmiel
          password: ${{ secrets.kadmiel }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
